<!DOCTYPE html>
<html>
    <head>
        <title>Freemarker</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div>Some content of a freemarker template...</div>
        <ul>
            <li><a href="/qw">Quasar with Webpack</a></li>
            <li><a href="/qv">Quasar with Vite</a></li>
        </ul>
    </body>
</html>
